// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itchfpnqnbxnqxgizjai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0Y2hmcG5xbmJ4bnF4Z2l6amFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDY4NDEsImV4cCI6MjA2NTU4Mjg0MX0.6ViurQjY2oULWP-Jjm-hLJCwgHEpgSJUXxAhayFTvc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);